# Generated by Django 4.2.4 on 2023-08-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hotel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
