# Generated by Django 4.1.6 on 2023-08-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_hotel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='amanity_name',
            new_name='amenity_name',
        ),
    ]
