# Generated by Django 4.1.6 on 2023-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_amanity_name_amenities_amenity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
