# Generated by Django 4.1.6 on 2023-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hotel_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimages',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='hotelimages',
            name='update_at',
        ),
        migrations.AddField(
            model_name='amenities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotelimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_type',
            field=models.CharField(choices=[('pre_paid', 'pre paid'), ('post_paid', 'post paid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
