# Generated by Django 4.1.6 on 2023-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_images_hotelimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='actual_price',
            field=models.IntegerField(default=1000),
        ),
    ]
