# Generated by Django 4.1.6 on 2023-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hotel_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
