# Generated by Django 4.1.6 on 2023-08-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_hotel_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimages',
            old_name='image',
            new_name='images',
        ),
    ]
