# Generated by Django 4.1.6 on 2023-08-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_image_hotelimages_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimages',
            old_name='images',
            new_name='image',
        ),
    ]
