# Generated by Django 4.1.6 on 2023-08-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_images_hotelimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage', max_digits=5),
        ),
    ]
