# Generated by Django 4.1.6 on 2023-08-24 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
