# Generated by Django 4.1.6 on 2023-08-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contact_number_alter_hotelbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
